-- AAA-AI: promo codes, premium time, and YouTube subscription verification.

-- Premium expiry (epoch millis). 0 / NULL = not premium.
ALTER TABLE users ADD COLUMN premium_until INTEGER NOT NULL DEFAULT 0;

-- Promo codes generated by the background Admin AI.
CREATE TABLE IF NOT EXISTS promo_codes (
  code TEXT PRIMARY KEY,
  premium_days INTEGER NOT NULL DEFAULT 7,
  max_redemptions INTEGER NOT NULL DEFAULT 30,
  redeemed INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1
);

-- One redemption row per (code, user); enforces "one use per user".
CREATE TABLE IF NOT EXISTS promo_redemptions (
  code TEXT NOT NULL,
  uid TEXT NOT NULL,
  ts INTEGER NOT NULL,
  PRIMARY KEY (code, uid)
);

-- YouTube subscription verification (per user, via their own OAuth consent).
CREATE TABLE IF NOT EXISTS yt_subs (
  uid TEXT PRIMARY KEY,
  subscribed INTEGER NOT NULL DEFAULT 0,
  checked_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_promo_redeem_uid ON promo_redemptions(uid);
CREATE INDEX IF NOT EXISTS idx_promo_active ON promo_codes(active);
